### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by MadsBock** [MercantecData/serverside-programmering-Clemmensen#1]
Jeg vil gerne have du laver en pull request hvori du specificerer i punktform hvilke af opgaverne på learnspace der er at finde i din portfolio på nuværende tidspunkt i færdig form. 

Fremadrettet vil jeg gerne bede dig lave en pull request når du er færdig med en ny opgave.

**Comment by Clemmensen** [comment]
PR for issue raised, awaiting review:
https://github.com/MercantecData/serverside-programmering-Clemmensen/pull/2

**Comment by MadsBock** [comment]
Review Passed
